---
title       : Testing Sabermetrics and Conventional Baseball Statistics
subtitle    : Tool to see how well sabermetrics and conventional baseball statistics predict team statistics
author      : Owen Byrne
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : standalone    # {standalone, draft}
knit        : slidify::knit2slides

---

## History of Sabermetrics

1. Bill James disliked conventional baseball statistics because they weren't actually useful
2. Invented his own stats - called "sabermetrics".
3. Concept made famous by "Moneyball."
4. "Runs Created" was the first "sabermetric"

---

## Runs Created

1. Compares individual players to estimate their value to their team.
2. Simple Example - Miguel Tejada was the American League Most Valuable Player in 2002 (determined by voting)
3. Use Advanced Runs Created (using all readily available statistics) to rank AL hitters

---

## American League Hitters (2002) ranked by Advanced Runs Created

```{r, echo=FALSE}
library(UsingR)
batting_copy <- batting
colnames(batting_copy) <- c('playerID', 'yearID', 'stintID', 'teamID', 'lgID', 'Games','AtBats','Runs',
                       'Hits','Doubles','Triples','HomeRuns','RBIs','StolenBases','CaughtStealing', 
                       'BasesOnBalls','StrikeOuts','IntentionalBasesOnBalls', 
                       'HitByPitch', 'SacrificeHits', 'SacrificeFlies', 'GroundIntoDoublePlays')

batting_copy$TotalBases <- batting_copy$Hits + batting_copy$Doubles + batting_copy$Triples*2 + batting_copy$HomeRuns*3
batting_copy$RunsCreatedAdvanced <- ((batting_copy$Hits+batting_copy$BasesOnBalls-batting_copy$CaughtStealing+batting_copy$HitByPitch-batting_copy$GroundIntoDoublePlays)*(batting_copy$TotalBases+.26*(batting_copy$BasesOnBalls-batting_copy$IntentionalBasesOnBalls+batting_copy$HitByPitch) + .52*(batting_copy$SacrificeHits+batting_copy$SacrificeFlies+batting_copy$StolenBases)))/(batting_copy$AtBats+batting_copy$BasesOnBalls+batting_copy$HitByPitch+batting_copy$SacrificeHits+batting_copy$SacrificeFlies)
al_batting <- batting_copy[batting_copy$lgID=="AL",]
al_batting[order(-al_batting$RunsCreatedAdvanced),c("playerID", "teamID", "RunsCreatedAdvanced")][1:15,]
```

---

## Conclusion

1. According to "AdvancedRunsCreated", Miguel Tejada (tejadmi01 OAK) was only the 12th best hitter in the American League in 2002. Jim Thome (thomeji01    CLE), Alex Rodriguez (rodrial01    TEX) or Jason Giambi (giambja01    NYA) would have been better choices for American League MVP.

### Shiny Application
1. By aggregating the players on the team, essentially bypass the main purpose of Sabermetrics
2. Nearly all statistics when aggregated provide predictive value of team results
3. One exception is "triples" - most likely because they're pretty rare.
4. But still a useful validation of Sabermetrics
5. [Further Reading](http://en.wikipedia.org/wiki/Sabermetrics)
